version: '2'

services:
  jenkins:
    image: jenkins-slave
    container_name: "jenkins-slave"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
     # JENKINS_HOME: "/data/jenkins"
    ports:
      - "2222:22"

